name: "DOCKER Update renv Cache"

on:
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:
    inputs:
      name:
        description: 'Who triggered this build?'
        required: true
        default: 'Maintainer (via GitHub)'
  pull_request:
    types:
      - closed
jobs:
  update-renv-cache:
    name: "Update renv Cache"
    if: |
      github.event_name == 'schedule' ||
      (
        github.event.pull_request.merged == true &&
        contains(
          join(github.event.pull_request.labels.*.name, ','),
          'type: package cache'
        )
      )
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pages: write
    container:
      image: carpentries/workbench-docker:${{ vars.WORKBENCH_TAG || 'latest' }}
      env:
        WORKBENCH_PROFILE: "ci"
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        RENV_PATHS_ROOT: /home/rstudio/lesson/renv
      volumes:
        - ${{ github.workspace }}:/home/rstudio/lesson
      options: --cpus 2
    steps:
      - name: "Checkout Lesson"
        uses: actions/checkout@v4

      - name: Current env
        run: env | sort

      - name: Debugging Info
        run: |
          echo "Current Directory: $(pwd)"
          ls -lah /home/rstudio/.workbench
          ls -lah $(pwd)
          Rscript -e 'sessionInfo()'

      - name: Mark Repository as Safe
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Check if renv Exists
        id: check-renv
        run: |
          if [ -d "/home/rstudio/lesson/renv" ]; then
            echo "RENV_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RENV_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Setup Lesson Dependencies
        if: env.RENV_EXISTS == 'true'
        run: |
          Rscript /home/rstudio/.workbench/setup_lesson_deps.R

      - name: Fortify renv Cache
        if: env.RENV_EXISTS == 'true'
        run: |
          Rscript /home/rstudio/.workbench/fortify_renv_cache.R

      - name: Cache renv Directory
        if: env.RENV_EXISTS == 'true'
        uses: actions/cache@v4
        with:
          path: /home/rstudio/lesson/renv
          key: ${{ runner.os }}-${{ inputs.cache-version }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys:
            ${{ runner.os }}-${{ inputs.cache-version }}-renv-
