name: "DOCKER Build and Deploy Site"

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:
    inputs:
      name:
        description: 'Who triggered this build?'
        required: true
        default: 'Maintainer (via GitHub)'
      reset:
        description: 'Reset cached markdown files'
        required: false
        default: false
        type: boolean
jobs:
  full-build:
    name: "Build Full Site"
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pages: write
    container:
      image: carpentries/workbench-docker:${{ vars.WORKBENCH_TAG || 'latest' }}
      env:
        WORKBENCH_PROFILE: "ci"
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        RENV_PATHS_ROOT: /home/rstudio/lesson/renv
      volumes:
        - ${{ github.workspace }}:/home/rstudio/lesson
      options: --cpus 1
    steps:
      - name: "Checkout Lesson"
        uses: actions/checkout@v4

      - name: Check if renv Exists
        id: check-renv
        run: |
          if [ -d "/home/rstudio/lesson/renv" ]; then
            echo "RENV_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RENV_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Set renv Cache Version
        if: env.RENV_EXISTS == 'true'
        run: |
          if [ -z "$CACHE_VERSION" ]; then
            echo "RENV_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "RENV_VERSION=$CACHE_VERSION" >> $GITHUB_ENV
          fi

      - name: Current env
        run: env | sort

      - name: Debugging Info
        run: |
          echo "Current Directory: $(pwd)"
          ls -lah /home/rstudio/.workbench
          ls -lah $(pwd)
          Rscript -e 'sessionInfo()'

      - name: Mark Repository as Safe
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Setup Lesson Dependencies
        run: |
          Rscript /home/rstudio/.workbench/setup_lesson_deps.R

      - name: Restore renv from cache
        uses: actions/cache@v4
        with:
          path: /home/rstudio/lesson/renv
          key: renv-${{ runner.os }}-${{ env.RENV_VERSION }}
          restore-keys: |
            renv-${{ runner.os }}-
            
      - name: Restore renv Dependencies
        if: env.RENV_EXISTS == 'true'
        run: |
          lsn_path <- fs::path(Sys.getenv("GITHUB_WORKSPACE", getwd()))
          renv_lib  <- renv::paths$library(project = lsn_path)
          renv_lock <- renv::paths$lockfile(project = lsn_path)
          renv::restore(project = lsn_path, library = renv_lib, lockfile = renv_lock, prompt = FALSE)
        shell: Rscript {0}

      - name: Run Container and Build Site
        run: |
          library(sandpaper)
          sandpaper::package_cache_trigger(TRUE)
          sandpaper:::ci_deploy(reset = TRUE)
        shell: Rscript {0}
